apiVersion: gateway.nginx.org/v1alpha1
kind: SnippetsFilter
metadata:
  name: accept-ip-sni
  namespace: {{ .Release.Namespace }}
spec:
  snippets:
    - context: http.server.location
      value: |
        # Override standard headers to ensure Port and Proto are correct
        #proxy_set_header Host $http_host;
        #proxy_set_header X-Forwarded-Host $http_host;
        #proxy_set_header X-Forwarded-Proto https;
        #proxy_set_header X-Forwarded-Port $server_port;
        #proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        #proxy_set_header X-Real-IP $remote_addr;

        # WebSocket support
        #proxy_set_header Upgrade $http_upgrade;
        #proxy_set_header Connection "upgrade";

        # 업로드 크기 제한 해제(또는 크게)
        client_max_body_size 0;

        # (선택) 업로드/프록시 버퍼링 꺼서 스트리밍 업로드에 유리
        proxy_request_buffering off;

        # (선택) 읽기/쓰기 타임아웃 늘리기(큰 파일/느린 회선)
        proxy_read_timeout 3600s;
        proxy_send_timeout 3600s;